dependency-dir: ../lib

depends:
  - chibios-syscalls
  - cmp
  - cmp_mem_access
  - error
  - crc
  - version
  - quadramp

target.arm:
  - src/main.c
  - src/debug.c
  - src/board.c
  - src/vl6180x/vl6180x.c
  - src/vl6180x/vl6180x_chibios.c
  - src/stubs.cpp
  - src/uavcan/node.cpp
  - src/bootloader_config.c
  - ../lib/can-bootloader/config.c

templates:
    app_src.mk.jinja: app_src.mk
